import { ImageSourcePropType } from 'react-native';

export interface ThemePreview {
  id: string;
  name: string;
  background: string;
  surface: string;
  accent: string;
  text: string;
  textMuted: string;
  border: string;
  isPremium: boolean;
  trialHours: number;
  backgroundImage?: ImageSourcePropType | null;
}

export const builtInThemes: ThemePreview[] = [
  {
    id: 'midnight',
    name: 'Midnight',
    background: '#0d0d0f',
    surface: '#1a1a1d',
    accent: '#7cebff',
    text: '#f2f2f2',
    textMuted: '#9a9a9e',
    border: '#2a2a2e',
    isPremium: false,
    trialHours: 0,
  },
  {
    id: 'slate',
    name: 'Slate',
    background: '#14171a',
    surface: '#20242a',
    accent: '#5fd4c1',
    text: '#e6e8ea',
    textMuted: '#8d9296',
    border: '#2c3238',
    isPremium: false,
    trialHours: 0,
  },
  {
    id: 'grayscale',
    name: 'Grayscale',
    background: '#161616',
    surface: '#232323',
    accent: '#c9c9c9',
    text: '#f0f0f0',
    textMuted: '#8a8a8a',
    border: '#333333',
    isPremium: false,
    trialHours: 0,
  },
  {
    id: 'newspaper',
    name: 'Newspaper',
    background: '#f4f1ea',
    surface: '#e8e3d8',
    accent: '#1a1a1a',
    text: '#1c1c1c',
    textMuted: '#6e6a62',
    border: '#d4cdbb',
    isPremium: false,
    trialHours: 0,
  },
  {
    id: 'aqua',
    name: 'Aqua',
    background: '#071a24',
    surface: '#0f2a38',
    accent: '#3ec9f0',
    text: '#e4f6fc',
    textMuted: '#7ba7b8',
    border: '#164256',
    isPremium: false,
    trialHours: 0,
  },
  {
    id: 'underwater',
    name: 'Underwater',
    background: '#071a24',
    surface: '#0f2a38',
    accent: '#3ec9f0',
    text: '#e4f6fc',
    textMuted: '#7ba7b8',
    border: '#164256',
    isPremium: true,
    trialHours: 12,
    backgroundImage: require('../../assets/images/underwater.jpg'),
  },
  {
    id: 'warmth',
    name: 'Warmth',
    background: '#1a0a06',
    surface: '#2b120a',
    accent: '#ff5a2e',
    text: '#fbe8e0',
    textMuted: '#b08172',
    border: '#3d1c10',
    isPremium: false,
    trialHours: 0,
  },
  {
    id: 'campfire',
    name: 'Campfire',
    background: '#1a0a06',
    surface: '#2b120a',
    accent: '#ff5a2e',
    text: '#fbe8e0',
    textMuted: '#b08172',
    border: '#3d1c10',
    isPremium: true,
    trialHours: 12,
    backgroundImage: require('../../assets/images/campfire.jpg'),
  },
  {
    id: 'gale',
    name: 'Gale',
    background: '#eef4f2',
    surface: '#dfeae6',
    accent: '#4fb59a',
    text: '#233631',
    textMuted: '#6f8b83',
    border: '#c6d9d3',
    isPremium: false,
    trialHours: 0,
  },
  {
    id: 'breeze',
    name: 'Breeze',
    background: '#eef4f2',
    surface: '#dfeae6',
    accent: '#4fb59a',
    text: '#233631',
    textMuted: '#6f8b83',
    border: '#c6d9d3',
    isPremium: true,
    trialHours: 12,
    backgroundImage: require('../../assets/images/breeze.jpg'),
  },
  {
    id: 'soil',
    name: 'Soil',
    background: '#1c1712',
    surface: '#2b241c',
    accent: '#b3833f',
    text: '#ece2d2',
    textMuted: '#96876f',
    border: '#3d3325',
    isPremium: false,
    trialHours: 0,
  },
  {
    id: 'earth',
    name: 'Earth',
    background: '#1c1712',
    surface: '#2b241c',
    accent: '#b3833f',
    text: '#ece2d2',
    textMuted: '#96876f',
    border: '#3d3325',
    isPremium: true,
    trialHours: 12,
    backgroundImage: require('../../assets/images/earth.jpg'),
  },
  {
    id: 'astro',
    name: 'Astro',
    background: '#0b0c1e',
    surface: '#151833',
    accent: '#8b7fff',
    text: '#e6e4ff',
    textMuted: '#7d7aa8',
    border: '#242850',
    isPremium: false,
    trialHours: 0,
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    background: '#0b0c1e',
    surface: '#151833',
    accent: '#8b7fff',
    text: '#e6e4ff',
    textMuted: '#7d7aa8',
    border: '#242850',
    isPremium: true,
    trialHours: 12,
    backgroundImage: require('../../assets/images/galaxy.jpg'),
  },
  {
    id: 'nature',
    name: 'Nature',
    background: '#f1f6ee',
    surface: '#e1ebd9',
    accent: '#6a9955',
    text: '#2c3826',
    textMuted: '#7d8f70',
    border: '#cfe0c2',
    isPremium: false,
    trialHours: 0,
  },
  {
    id: 'dewdrop',
    name: 'Dewdrop',
    background: '#f1f6ee',
    surface: '#e1ebd9',
    accent: '#6a9955',
    text: '#2c3826',
    textMuted: '#7d8f70',
    border: '#cfe0c2',
    isPremium: false,
    trialHours: 0,
    backgroundImage: require('../../assets/images/dewdrop.jpg'),
  },
  {
    id: 'abyss',
    name: 'Abyss',
    background: '#0c0e12',
    surface: '#161a22',
    accent: '#3a6fd8',
    text: '#dde3ec',
    textMuted: '#6b7684',
    border: '#232a36',
    isPremium: false,
    trialHours: 0,
  },
  {
    id: 'hadal',
    name: 'Hadal',
    background: '#0c0e12',
    surface: '#161a22',
    accent: '#3a6fd8',
    text: '#dde3ec',
    textMuted: '#6b7684',
    border: '#232a36',
    isPremium: true,
    trialHours: 12,
    backgroundImage: require('../../assets/images/hadal.jpg'),
  },
  {
    id: 'seafoam',
    name: 'Seafoam',
    background: '#eef7f4',
    surface: '#dcefe7',
    accent: '#4fbf9f',
    text: '#213b34',
    textMuted: '#6f958a',
    border: '#c3e2d7',
    isPremium: true,
    trialHours: 12,
  },
  {
    id: 'coral',
    name: 'Coral',
    background: '#fdf0ec',
    surface: '#fbdfd6',
    accent: '#f2946b',
    text: '#402a22',
    textMuted: '#9c7a6d',
    border: '#f5cec0',
    isPremium: true,
    trialHours: 12,
  },
  {
    id: 'queen',
    name: 'Queen',
    background: '#fdfbfa',
    surface: '#f7e9e8',
    accent: '#c9152e',
    text: '#2a1414',
    textMuted: '#9c7a7a',
    border: '#eecfcf',
    isPremium: true,
    trialHours: 12,
  },
  {
    id: 'alice',
    name: 'Alice',
    background: '#eef2fb',
    surface: '#dde6f5',
    accent: '#5b7fd6',
    text: '#26314a',
    textMuted: '#7a88a8',
    border: '#c9d6ee',
    isPremium: true,
    trialHours: 12,
  },
  {
    id: 'cheshire',
    name: 'Cheshire',
    background: '#241a2e',
    surface: '#3a2748',
    accent: '#d977c9',
    text: '#f2e6f5',
    textMuted: '#a488ac',
    border: '#4d3560',
    isPremium: true,
    trialHours: 12,
  },
  {
    id: 'ultra-dark',
    name: 'Ultra Dark',
    background: '#000000',
    surface: '#0a0a0a',
    accent: '#ffffff',
    text: '#f5f5f5',
    textMuted: '#6e6e6e',
    border: '#161616',
    isPremium: true,
    trialHours: 12,
  },
  {
    id: 'sakura',
    name: 'Sakura',
    background: '#fdf1f4',
    surface: '#fbe3ea',
    accent: '#e893ac',
    text: '#4a2e35',
    textMuted: '#9c7b83',
    border: '#f3cdd9',
    isPremium: true,
    trialHours: 12,
  },
  {
    id: 'parchment',
    name: 'Parchment',
    background: '#f2e8d5',
    surface: '#e8dcc3',
    accent: '#8a6f4b',
    text: '#3a3226',
    textMuted: '#7a6f5c',
    border: '#d9cba9',
    isPremium: true,
    trialHours: 12,
  },
  {
    id: 'retro',
    name: 'Retro',
    background: '#fdf3e3',
    surface: '#f7e3c4',
    accent: '#e0633f',
    text: '#2e2a25',
    textMuted: '#8a7d68',
    border: '#e8d3a8',
    isPremium: true,
    trialHours: 12,
    backgroundImage: require('../../assets/images/retro.jpg'),
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    background: '#0a0014',
    surface: '#160a24',
    accent: '#ff2fb0',
    text: '#e8e2ff',
    textMuted: '#8f7fae',
    border: '#2e1a44',
    isPremium: true,
    trialHours: 12,
    backgroundImage: require('../../assets/images/cyberpunk.jpg'),
  },
  {
    id: 'neo',
    name: 'Neo',
    background: '#0a0f0a',
    surface: '#0f170f',
    accent: '#39ff6a',
    text: '#c8f5cf',
    textMuted: '#5c9464',
    border: '#1c2c1c',
    isPremium: true,
    trialHours: 12,
    backgroundImage: require('../../assets/images/neo.jpg'),
  },
];